[package]
name = "threadid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
crossbeam = "0.8"
ctrlc = "3.4.0"
env_logger = "0.10.0"
